# AUTOINSTALLER
## APPLICATION INSTALLATION PROCESS
### TARGET LIST
target=[
    # index,setup_file,install_file,install_flag,desktop_shortcut_flag
    # `index`: indexing of the target, not indexed won't be added to installation, duplicated indexing throws error
    # `setup_file`: relative path to the setup file
        ## You may name it as you whatever you want, install file will get the exact name of setup file.
    # `install_file`: relative path to the installation script
        ## Can not rename, must be compiled with `compile-au2exe.ps1`
    # `install_flag`: whether the installation will be installed
        ## `true`: Install the application
        ## `false`: Do not install the application
    # `desktop_shortcut_flag:` whether the desktop shortcut will be created
        ## `true`: Create desktop shortcut
        ## `false`: Do not create desktop shortcut
    0,"Browsers/chrome-standalone.exe","Browsers/install_chrome-standalone.exe",true,true;
    1,"Environment/Java/java.exe","Environment/Java/install_java.exe",true,false;
    2,"Environment/Python/python.exe","Environment/Python/install_python.exe",true,false;
    3,"Environment/VCRedist/vcredist-AIO.exe","Environment/VCRedist/install_vcredist.exe",true,false;
    4,"Environment/IDEs/vs.exe","Environment/IDEs/install_vs.exe",false,false;
    5,"Tools/Archivers/7z.exe","Tools/Archivers/install_7z.exe",true,true;
    6,"Tools/Archivers/winrar.exe","Tools/Archivers/install_winrar.exe",true,true;
    7,"Tools/Editors/notepadpp.exe","Tools/Editors/install_notepadpp.exe",true,true;
    8,"Tools/Editors/vscode.exe","Tools/Editors/install_vscode.exe",true,true;
    9,"Utilities/MediaPlayers/mpc.exe","Utilities/MediaPlayers/install_mpc.exe",true,true;
    10,"Utilities/VietnameseKeyboards/unikey.exe","Utilities/VietnameseKeyboards/install_unikey.exe",true,true;
    11,"Tools/ScreenRecorders/obs.exe","Tools/ScreenRecorders/install_obs.exe",true,true;
    12,"Tools/DesktopSupporters/ultraviewer.exe","Tools/DesktopSupporters/install_ultraviewer.exe",true,true;
    13,"Tools/DesktopSupporters/teamviewer.exe","Tools/DesktopSupporters/install_teamviewer.exe",true,true;
    14,"Office/Office2024/office2024.exe","Office/Office2024/install_office2024.exe",true,true;
    15,"Office/LibreOffice/libreoffice.msi","Office/LibreOffice/install_libreoffice.exe",true,true;
    16,"Socials/discord.exe","Socials/install_discord.exe",true,true;
    17,"Socials/zalo.exe","Socials/install_zalo.exe",true,true;
    18,"Antivirus/kaspersky.exe","Antivirus/install_kaspersky.exe",false,true;
    19,"Utilities/FileExplorer/shell.msi","Utilities/FileExplorer/install_shell.exe",true,false;
    20,"Utilities/Fonts","Utilities/Fonts/install_fonts.exe",true,false;
];
### CONFIGURATION
## max_iteration: maximum number of iterations (should be at least 0)
max_iteration=2;
## log_path: path to the log file
log_path=C:/Auto-installer/install-apps.log;
## clean invalid/uninstallable/already-installed fonts
clean_after_installing=true;
# END